services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: "$$2a$$10$$hSWAHjNzBDip2EocURcjxexTRw4LDNhw4Aec5lPHxfXQL342FONgm"
      # MODPACK_PLATFORM: AUTO_CURSEFORGE
      # CF_MODPACK_MANIFEST: /manifests/manifest.json
      # CF_SLUG: "custom"
      CF_SLUG: beyond-depth
      CF_FILE_ID: 6699121
      EULA: TRUE
      MAX_MEMORY: 15G
      INIT_MEMORY: 8G
      MAX_PLAYERS: 10
      USE_MEOWICE_FLAGS: "true"
      ALLOW_FLIGHT: "TRUE"
      PLAYER_IDLE_TIMEOUT: 300
      DIFFICULTY: hard
    tty: true
    stdin_open: true
    restart: unless-stopped
    mem_limit: 15g
    cpu_count: 6
    volumes:
      - leserveurdemerdela:/data

  ftp-container:
    image: kibatic/proftpd
    network_mode: host
    restart: always
    environment:
      FTP_LIST: "username:password"
      USERADD_OPTIONS: "-o --gid 33 --uid 33"  # Retour aux IDs originaux (www-data)
      FTP_PASSIVE_PORTS: "21100-21110"
      # Ajout d'une commande d'initialisation pour créer le répertoire et définir les permissions
    volumes:
      - leserveurdemerdela:/data
    user: root  # Ajout important pour avoir les permissions nécessaires
    command: >
      sh -c "
      addgroup --gid 33 ftpgroup &&
      adduser --uid 33 --gid 33 --home /data --shell /bin/bash --disabled-password username &&
      chown -R username:ftpgroup /data &&
      chmod 755 /data &&
      proftpd --nodaemon"


volumes:
  leserveurdemerdela: