version: "3.8"

services:
  mc:
    container_name: walkercraft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      # MODPACK_PLATFORM: AUTO_CURSEFORGE
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: '$2a$10$qnrppGeiuiybVcBBs0uiy.Qev2QtZYC6zIfP0PLSj1//YuNMjsmk2'
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/beyond-depth/files/6584481
      EULA: "TRUE"
      VERSION: 1.20.1
      MEMORY: 10G
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  data: