version: "3.8"

services:
  mc:
    container_name: walkercraft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      CF_API_KEY: $2a$10$KJpoLC4rPM.n5ZOPDYhRyuuvjd5gND7VSCxhnDRfODsqHZ54cNIN2
      EULA: "TRUE"
      TYPE: AUTO_CURSEFORGE
      VERSION: 1.20.1
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/beyond-depth/files/6584481
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data

volumes:
  data: