version: "3.8"

services:
  mc:
    container_name: walkercraft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      TYPE: AUTO_CURSEFORGE
      VERSION: 47.4.0
      CF_API_KEY: ${API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/beyond-depth/files/6584481
      EULA: "TRUE"
      MEMORY: 10G
      MAX_PLAYERS: 50
      CF_SERVER_MOD: forge-1.20.1-47.4.0-installer.jar
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
