services:
  mc:
    image: itzg/minecraft-server:java17
    ports:
      - 25565:25565
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: "$$2a$$10$$hSWAHjNzBDip2EocURcjxexTRw4LDNhw4Aec5lPHxfXQL342FONgm"
      # MODPACK_PLATFORM: AUTO_CURSEFORGE
      # CF_MODPACK_MANIFEST: /manifests/manifest.json
      # CF_SLUG: "custom"
      CF_SLUG: beyond-depth
      CF_FILE_ID: 6699121
      EULA: TRUE
      MAX_MEMORY: 13G
      INIT_MEMORY: 8G
      MAX_PLAYERS: 10
      USE_MEOWICE_FLAGS: true
    tty: true
    stdin_open: true
    restart: unless-stopped
    mem_limit: 13g
    volumes:
      - leserveurdemerdela:/data

volumes:
  leserveurdemerdela: