services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: "$$2a$$10$$xkJmMycGUpJgBJcd0nUd.eCeeOohMG1wXOh0gk25nFG3BmdWNVjiO"
      CF_MODPACK_MANIFEST: /manifests/manifest.json
      CF_SLUG: "custom"
      EULA: "TRUE"
      MEMORY: 14G
      INIT_MEMORY: 14G
      MAX_PLAYERS: 10
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - mcdata:/data
      - ./manifests:/manifests:ro


volumes:
  mcdata: {}