version: "3.8"

services:
  mc:
    container_name: walkercraft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      VERSION: 1.20.1
      MODS_FILE: /extras/mods.txt
      CF_SLUG: beyond-depth
      CF_FILE_ID: "6584481"
      CF_API_KEY: $2a$10$ZO0t2XdWGUrvNaO/vDH6we86H.ajJadvSyV2gntlyECUlleLxDRz6
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
      - ./mods.txt:/extras/mods.txt:ro

volumes:
  data: