services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: "$$2a$$10$$hSWAHjNzBDip2EocURcjxexTRw4LDNhw4Aec5lPHxfXQL342FONgm"
      CF_MODPACK_MANIFEST: /manifests/manifest.json
      CF_SLUG: "custom"
      EULA: TRUE
      MEMORY: 14G
      INIT_MEMORY: 14G
      MAX_PLAYERS: 50
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - leserveurdemerdela:/data
      - ./manifests:/manifests:ro
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 14G
        reservations:
          cpus: 4
          memory: 8G


volumes:
  leserveurdemerdela: